projects/ContactCenter/ContactCenter/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ContactCenter.Models;
public class LoginViewModel
{
    [Required]
    [Display(Name = "Логин")]
    public string UserName { get; set; }

    [Required]
    // ReSharper disable once Mvc.TemplateNotResolved
    [UIHint("password")]
    [Display(Name = "Пароль")]
    public string Password { get; set; }

    [Display(Name = "Запомнить меня?")]
    public bool RememberMe { get; set; }
}

projects/ContactCenter/ContactCenter/Models/ViewComponents/SidebarViewComponent.cs
using ContactCenter.Domain;
using Microsoft.AspNetCore.Mvc;

namespace c;

public class SidebarViewComponent : ViewComponent
{
    private readonly DataManager _dataManager;

    public SidebarViewComponent(DataManager dataManager)
    {
        _dataManager = dataManager;
    }

    public Task<IViewComponentResult> InvokeAsync()
    {
        return Task.FromResult((IViewComponentResult) View("Default", _dataManager.ServiceItemsRepository.GetServiceItems()));
    }
}

projects/ContactCenter/ContactCenter/Areas/Admin/Controllers/HomeController.cs
using ContactCenter.Domain;
using Microsoft.AspNetCore.Mvc;

namespace ContactCenter.Areas.Admin.Controllers;

[Area("Admin")]
public class HomeController : Controller
{
    private readonly DataManager _dataManager;

    public HomeController(DataManager dataManager)
    {
        _dataManager = dataManager;
    }

    public IActionResult Index()
    {
        return View(_dataManager.ServiceItemsRepository.GetServiceItems());
    }
}

projects/ContactCenter/ContactCenter/Areas/Admin/Controllers/ServiceItemsController.cs
using ContactCenter.Domain;
using ContactCenter.Domain.Entities;
using ContactCenter.Service;
using Microsoft.AspNetCore.Mvc;

namespace ContactCenter.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager _dataManager;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            _dataManager = dataManager;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : _dataManager.ServiceItemsRepository.GetServiceItem(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile? titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    
                    using var stream = new FileStream(Path.Combine(_hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create);
                    titleImageFile.CopyTo(stream);
                }
                _dataManager.ServiceItemsRepository.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            _dataManager.ServiceItemsRepository.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

projects/ContactCenter/ContactCenter/Areas/Admin/Controllers/TextFieldsController.cs
using ContactCenter.Domain;
using ContactCenter.Domain.Entities;
using ContactCenter.Service;
using Microsoft.AspNetCore.Mvc;

namespace ContactCenter.Areas.Admin.Controllers;

[Area("Admin")]
public class TextFieldsController : Controller
{
    private readonly DataManager _dataManager;
    public TextFieldsController(DataManager dataManager)
    {
        _dataManager = dataManager;
    }

    public IActionResult Edit(string codeWord)
    {
        var entity = _dataManager.TextFieldsRepository.GetTextField(codeWord);
        return View(entity);
    }

    [HttpPost]
    public IActionResult Edit(TextField model)
    {
        if (ModelState.IsValid)
        {
            _dataManager.TextFieldsRepository.SaveTextField(model);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
        return View(model);
    }
}

projects/ContactCenter/ContactCenter/Controllers/AccountController.cs
using ContactCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ContactCenter.Controllers;

[Authorize]
public class AccountController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly SignInManager<IdentityUser> _signInManager;
    public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    [AllowAnonymous]
    public IActionResult Login(string returnUrl)
    {
        ViewBag.returnUrl = returnUrl;
        return View(new LoginViewModel());
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.FindByNameAsync(model.UserName);
            if (user != null)
            {
                await _signInManager.SignOutAsync();
                    
                var result = await _signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                if (result.Succeeded)
                {
                    return Redirect(returnUrl ?? "/");
                }
            }
            ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
        }
        return View(model);
    }

    [Authorize]
    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }
}

projects/ContactCenter/ContactCenter/Controllers/HomeController.cs
using ContactCenter.Domain;
using Microsoft.AspNetCore.Mvc;

namespace ContactCenter.Controllers;

public class HomeController : Controller
{
    private readonly DataManager _dataManager;
    public HomeController(DataManager dataManager)
    {
        _dataManager = dataManager;
    }
    
    public IActionResult Index()
    {
        return View(_dataManager.TextFieldsRepository.GetTextField("PageIndex"));
    }
    
    public IActionResult Contacts()
    {
        return View(_dataManager.TextFieldsRepository.GetTextField("PageContacts"));
    }
}

projects/ContactCenter/ContactCenter/Controllers/ServicesController.cs
using ContactCenter.Domain;
using ContactCenter.Service;
using Microsoft.AspNetCore.Mvc;

namespace ContactCenter.Controllers;

public class ServicesController : Controller
{
    private readonly DataManager _dataManager;
    private readonly ISmsService _smsService;
    private readonly ICallService _callService;

    public ServicesController(DataManager dataManager, ISmsService smsService, ICallService callService)
    {
        _dataManager = dataManager;
        _smsService = smsService;
        _callService = callService;
    }

    public IActionResult Index(Guid id)
    {
        if (id != default)
        {
            return View("Show", _dataManager.ServiceItemsRepository.GetServiceItem(id));
        }

        ViewBag.TextField = _dataManager.TextFieldsRepository.GetTextField("PageServices") ?? throw new InvalidOperationException();
        return View(_dataManager.ServiceItemsRepository.GetServiceItems());
    }

    [HttpGet]
    public IActionResult Call()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Call(string phoneNumber)
    {
        _callService.Call(phoneNumber);
        return View();
    }

    [HttpGet]
    public IActionResult Send()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Send(string phoneNumber, string textMessage)
    {
        var result = _smsService.Send(textMessage);
        ViewBag.Message = result
            ? $"Сообщение по номеру: {phoneNumber} успешно отправлено!"
            : $"Сообщение по номеру: {phoneNumber} не удалось отправить!";
        
        return View();
    }
    
    [HttpGet]
    public IActionResult Statistics()
    {
        return View();
    }
}

projects/ContactCenter/ContactCenter/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    const string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Доступные сервисы</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить сервис</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (var entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Сервисы</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

projects/ContactCenter/ContactCenter/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    const string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedOn" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>

<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

projects/ContactCenter/ContactCenter/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    const string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedOn" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

projects/ContactCenter/ContactCenter/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

projects/ContactCenter/ContactCenter/Views/Home/Index.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

projects/ContactCenter/ContactCenter/Views/Services/Call.cshtml
<div>
    <h2>
        Сервис совершения звонка
    </h2>
    <h1>
        @ViewBag.Message
    </h1>
    <form asp-controller="Services" asp-action="Call" method="post">
        <p>
            <label>Номер телефона</label><br/>
            <input type="text" name="phoneNumber"/>
        </p>
        <p>
            <label>Имя контакта</label><br/>
            <input type="text" name="phoneNumber"/>
        </p>
        <p>
            <input type="submit" value="Позвонить"/>
            <input type="submit" value="Сбросить"/>
        </p>
    </form>
</div>

projects/ContactCenter/ContactCenter/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (var entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="@entity.MetaDescription" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

projects/ContactCenter/ContactCenter/Views/Services/Send.cshtml
<div>
    <h2>
        Сервис отправки сообщения
    </h2>
    <h1>
        @ViewBag.Message
    </h1>
    <form asp-controller="Services" asp-action="Send" method="post">
        <p>
            <label>Номер телефона</label><br/>
            <input type="text" name="phoneNumber"/>
        </p>
        <p>
            <label>Сообщение</label><br/>
            <textarea name="textMessage"></textarea>
        </p>
        <p>
            <input type="submit" value="Отправить"/>
        </p>
    </form>
</div>

projects/ContactCenter/ContactCenter/Views/Services/Show.cshtml
@model ServiceItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>@Model.Title</h2>
</div>
<div>
    <form asp-area="" asp-controller="Services" asp-action="@Model.MetaDescription" method="post" enctype="multipart/form-data">
        <div class="div-box">
            <input asp-for="MetaKeywords" />
            <input type="submit" value="@Model.MetaTitle"/>
        </div>
    </form>
</div>

projects/ContactCenter/ContactCenter/Views/Services/Statistics.cshtml
<div>
    <h2>
        Сервис работы со статистикой
    </h2>
    <form asp-controller="Services" asp-action="Call" method="post">
        <p>
            <input type="checkbox" name="phoneNumber"/>
            <label>Статистика по конкретному дню</label><br/>
            <input type="date" name="phoneNumber"/>
        </p>
        <p>
            <input type="checkbox" name="phoneNumber"/>
            <label>Статистика в период </label><br/>
            <label>От </label>
            <input type="date" name="phoneNumber"/>
            <label> до </label>
            <input type="date" name="phoneNumber"/>
        </p>
        <p>
            <input type="checkbox" name="phoneNumber"/>
            <label>Получить всю статистику</label>
        </p>
        <p>
            <input type="submit" value="Получить"/>
        </p>
    </form>
</div>

projects/ContactCenter/ContactCenter/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<ServiceItem>

@if (Model?.Any() == true)
{
    <section>
        <h2>Доступные сервисы</h2>
        <ul class="small-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>
                        @entity.Title
                    </h4>
                    <p>
                        @entity.Subtitle
                    </p>
                </li>
            }
        </ul>
    </section>
}

projects/ContactCenter/ContactCenter/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>

projects/ContactCenter/ContactCenter/Views/Shared/FooterPartial.cshtml
<div id="footer-wrapper">
			<div class="container">
					<div class="col-12">
						<div id="copyright">
							&copy; Контакт-центр.
						</div>
					</div>
				</div>
			</div>

projects/ContactCenter/ContactCenter/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">Контакт-центр</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Сервисы</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        <a asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index">Панель администратора</a>
                    </nav>
                </header>
            </div>
        </div>
    </div>
</div>

projects/ContactCenter/ContactCenter/Views/Shared/Layout.cshtml
<!DOCTYPE HTML>
<html>
	<head>
		@await Html.PartialAsync("MetaTagsPartial")
		@await Html.PartialAsync("CssPartial")
	</head>
	<body>
	<div id="page-wrapper">
		@await Html.PartialAsync("HeaderPartial")
		<div id="main">
			<div class="container">
				<div class="row main-row">
					<div class="col-8 col-12-medium imp-medium">
						@RenderBody()
					</div>
				</div>
				@await Html.PartialAsync("SidebarPartial")
			</div>
		</div>
		@await Html.PartialAsync("FooterPartial")
	</div>
	@await Html.PartialAsync("ScriptsPartial")
	</body>
</html>

projects/ContactCenter/ContactCenter/Views/Shared/MetaTagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>Контакт-центр</title>
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description"/>
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords"/>
}

projects/ContactCenter/ContactCenter/Views/Shared/ScriptsPartial.cshtml
@* <script src="assets/js/jquery.min.js"></script> *@
@* <script src="assets/js/browser.min.js"></script> *@
@* <script src="assets/js/breakpoints.min.js"></script> *@
@* <script src="assets/js/util.js"></script> *@
@* <script src="assets/js/main.js"></script> *@

<script src="~/js/scripts.min.js" asp-append-version="true"></script>

projects/ContactCenter/ContactCenter/Views/Shared/SidebarPartial.cshtml
@using c
<div class="col-4 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

projects/ContactCenter/ContactCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
	<head>
		@await Html.PartialAsync("MetaTagsPartial")
		@await Html.PartialAsync("CssPartial")
	</head>
	<body>
	<div id="page-wrapper">
		@await Html.PartialAsync("HeaderPartial")
		<div id="main">
			<div class="container">
				<div class="row main-row">
					<div class="col-8 col-12-medium imp-medium">
						@RenderBody()
					</div>
					@await Html.PartialAsync("SidebarPartial")
				</div>
			</div>
		</div>
		@await Html.PartialAsync("FooterPartial")
	</div>
	@await Html.PartialAsync("ScriptsPartial")
	</body>
</html>

projects/ContactCenter/ContactCenter/Views/VewImports.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers